env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  react/prop-types: off,
  jsx-a11y/click-events-have-key-events: off,
  jsx-a11y/no-static-element-interactions: off,
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }],
}
